cartapp/urls.py
from django.urls import path
from . import views

app_name='cartapp'

urlpatterns=[
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('',views.cart_detail,name='cart_detail'),
    path('cart_remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('full_remove/<int:product_id>/', views.full_remove, name='full_remove'),

]

ecommerceapp/urls.py
from django.urls import path
from . import views
app_name='ecommerceapp'
urlpatterns=[
    path('',views.all_products,name='allproducts'),
    path('<slug:c_slug>/',views.all_products,name='products_by_category'),
    path('<slug:c_slug>/<slug:p_slug>/',views.prodetail,name='prodetail'),
    # path('',views.index,name='index'),
]

ecommerceproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('ecommerceapp/',include('ecommerceapp.urls')),
    path('searchapp/',include('searchapp.urls')),
    path('cartapp/',include('cartapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

searchapp/urls.py
from django.urls import path
from . import views

app_name='searchapp'
urlpatterns=[
    path('',views.search,name='search'),
]

cartapp/models.py
from django.db import models
from ecommerceapp.models import product
# Create your models here.
class cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)

    class Meta:
        db_table='cart'
        ordering=['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)

class cartitem(models.Model):
    pr=models.ForeignKey(product,on_delete=models.CASCADE)
    c=models.ForeignKey(cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)

    class Meta:
        db_table='cartitem'

    def sub_total(self):
        return self.pr.price * self.quantity

    def __str__(self):
        return '{}'.format(self.pr)

ecommerceapp/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    image=models.ImageField(upload_to='category_images',blank=True)

    class Meta:
        ordering=('name',)
        verbose_name = 'verbose_category'
        verbose_name_plural = 'verbose_categories'

    def get_url(self):
        return reverse('ecommerceapp:products_by_category',args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)

class product(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(category,on_delete=models.CASCADE)
    image=models.ImageField(upload_to='product_images',blank=True)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('ecommerceapp:prodetail',args=[self.category.slug,self.slug])

    class Meta:
        ordering=('name',)
        verbose_name = 'verbose_product'
        verbose_name_plural = 'verbose_products'

    def __str__(self):
        return '{}'.format(self.name)

searchapp/models.py
from django.db import models

# Create your models here.

cartapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from ecommerceapp.models import product
from .models import cart,cartitem
from django.core.exceptions import ObjectDoesNotExist
# Create your views here.

def c_id(request):
    c_data=request.session.session_key
    if not c_data:
        c_data=request.session.create()
    return c_data

def add_cart(request,product_id):
    p1=product.objects.get(id=product_id)
    try:
        c1=cart.objects.get(cart_id=c_id(request))
    except cart.DoesNotExist:
        c1=cart.objects.create(cart_id=c_id(request))
        c1.save()
    try:
        c_items=cartitem.objects.get(pr=p1,c=c1)
        if c_items.quantity < c_items.pr.stock:
            c_items.quantity += 1
        c_items.save()
    except cartitem.DoesNotExist:
        c_items=cartitem.objects.create(
            pr=p1,
            quantity=1,
            c=c1
        )
        c_items.save()
    return redirect('cartapp:cart_detail')


def cart_detail(request,total=0,counter=0,c_items=None):
    try:
        c1=cart.objects.get(cart_id=c_id(request))
        c_items=cartitem.objects.filter(c=c1,active=True)
        for i in c_items:
            total += (i.pr.price * i.quantity)
            counter += i.quantity

    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(c_items=c_items,total=total,counter=counter))



def cart_remove(request,product_id):
    c2=cart.objects.get(cart_id=c_id(request))
    p2=get_object_or_404(product,id=product_id)
    cart_items=cartitem.objects.get(pr=p2,c=c2)
    if cart_items.quantity > 1:
        cart_items.quantity -= 1
        cart_items.save()
    else:
        cart_items.delete()
    return redirect('cartapp:cart_detail')


def full_remove(request,product_id):
    c2 = cart.objects.get(cart_id=c_id(request))
    p2 = get_object_or_404(product, id=product_id)
    cart_items = cartitem.objects.get(pr=p2,c=c2)
    cart_items.delete()
    return redirect('cartapp:cart_detail')

ecommerceapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from . models import category,product
from django.core.paginator import Paginator, EmptyPage, InvalidPage


# Create your views here.
# def index(request):
#     return HttpResponse("hai buddy")

def all_products(request,c_slug=None):
    c_page=None
    products_list=None
    if c_slug!=None:
        c_page=get_object_or_404(category,slug=c_slug)
        products_list=product.objects.all().filter(category=c_page,available=True)
    else:
        products_list=product.objects.all().filter(available=True)
    paginator=Paginator(products_list,6)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    try:
        pro=paginator.page(page)
    except (EmptyPage,InvalidPage):
        pro=paginator.page(paginator.num_pages)
    return render(request,"cat.html",{"c_page":c_page,"pro":pro})

def prodetail(request,c_slug,p_slug):
    try:
        pro1=product.objects.get(category__slug=c_slug,slug=p_slug)
    except Exception as e:
        raise e
    return render(request,'product_detail.html',{'pro1':pro1})

searchapp/views.py
from django.shortcuts import render
from ecommerceapp.models import product
from django.db.models import Q
# Create your views here.


def search(request):
    p=None
    query=None
    if 'q' in request.GET:
        query=request.GET.get('q')
        p=product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))

    return render(request,'search.html',{'query':query,'p':p})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
      <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
      <script src="https://kit.fontawesome.com/2bdb8fac96.js" crossorigin="anonymous"></script>
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body class="roboto-black">
<div class="container">
    {% include 'header.html' %}
    {% include 'nav.html' %}
    {% block content %}
    {% endblock %}

</div>
<br></br>break

{% include 'footer.html' %}
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>



</body>
</html>

templates/cart.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
      this is the cart page
{% endblock %}

{% block title %}
       Cart!!!!
{% endblock %}


{% block content %}
{% if not c_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center mytitle">
            Your Cart Is Empty!!
        </h1>
        <br>
        <p class="text-center">
            Please click here <a href="{% url 'ecommerceapp:allproducts' %}">Click Here</a>
        </p>
    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center mytitle">
            Your Cart
        </h1>
        <br>
    </div>
</div>
{% endif %}
<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table mycustomtable">
            <thead class="mycustom_thead">
                <tr>
                    <th colspan="5">
                        Items!!
                    </th>
                </tr>
            </thead>
            <tbody>
            {% for i in c_items %}
            <tr>
                <td>
                    <a href="{{i.pr.get_url}}"><img src="{{i.pr.image.url}}"  alt="" style="width:100px;height:100px;" class="float-left rounded custom_image"></a>

                </td>
                <td class="text-lef">
                    {{i.pr.name}}
                    <br>
                    SKU: {{i.pr.id}}
                    <br>
                    Price: $ {{i.pr.price}}
                    <br>
                    Qty : {{i.quantity}} x $ {{i}}
                </td>
                <td>
                    $ {{i.sub_total}}
                </td>
                {% if i.quantity < i.pr.stock %}
                <td>
                    <a href="{% url 'cartapp:add_cart' i.pr.id %}"  class="custom_a"><i class="fa-solid fa-plus custom-icon"></i></a>
                    &nbsp;<a href="{% url 'cartapp:cart_remove' i.pr.id %}"  class="custom_a"><i class="fa-solid fa-minus custom-icon"></i></a>
                    &nbsp;<a href="{% url 'cartapp:full_remove' i.pr.id %}"  class="custom_icon"><i class="fa-solid fa-trash custom-icon"></i></a>

                </td>
                {% else %}
                <td>
                    &nbsp;<a href="{% url 'cartapp:cart_remove' i.pr.id %}"  class="custom_a"><i class="fa-solid fa-minus custom-icon"></i></a>
                    &nbsp;<a href="{% url 'cartapp:full_remove' i.pr.id %}"  class="custom_icon"><i class="fa-solid fa-trash custom-icon"></i></a>
                </td>
            </tr>
            {% endif %}
            {% endfor %}
            </tbody>
        </table>
    </div>
<div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
    <table class="table my_custom_table">
        <thead class="mycustom_thead">
        <tr>
            <th>
                Checkout
            </th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>
                please review your shopping cart items before proceeding with the order payment.
            </td>
        </tr>
        <tr>
            <td class="text-left">
                your total is : <strong> {{total}} </strong>
            </td>
        </tr>
        </tbody>
    </table>
    <div class="mx-auto">
        <a href="{% url 'ecommerceapp:allproducts' %}"  class="btn btn-secondary btn-block my_custom_button">Continue Shopping..</a>
    </div>
</div>
</div>
{% endblock %}

templates/cat.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if c_page %}
        {{c_page.description|truncatewords:155}}
    {% else %}
        welcome to the store...
    {% endif %}
{% endblock %}

{% block title %}
    {% if c_page %}
        {{c_page.name }}
    {% else %}
        check new collections..
    {% endif %}
{% endblock %}


{% block content %}
    {% if c_page %}
        <div>
            <div class="row myclass">
               <div class="mx-auto">
                <p><a href="{% url 'ecommerceapp:allproducts' %}">COLLECTIONS</a> </p>
               </div>
            </div>
        </div>
    {% endif %}
         <div class="mx-auto">
             {% if c_page %}
                 <img class="myimage" src="{{c_page.image.url}}" alt="{{c_page.name}}" style="width:1200px">
         </div> <br>
         <div>
             <h1 class="text-center mytitle">{{c_page.name}}</h1>
             <p class="text-justify ">{{c_page.description}}</p>
         </div>
             {% else %}
                  <div>
                      <img class="myimage myimagepadding " src="{% static 'images/banner.png' %}" alt="our products..." style="width:1200px">
                  </div><br>
         <div>
             <h1 class="text-center mytitle">New Collections...</h1>
         </div>
             {% endif %}
         <div class="container">
             <div class="row mx-auto">
                 {% for i in pro.object_list %}
                 <div class="my-bottom-margin col-9 col-sm-12 col-md-4  xol-lg-4">
                     <div class="card text-center" style="min-width:18rem">
                     <a href="{{i.get_url}}"><img class="card-img myimage" src="{{i.image.url}}"  alt="{{i.name}}"></a>
                     <div class="card-body">
                         <h4>{{i.name}}</h4>
                         <p>${{i.price}}</p>
                     </div>
                     </div>
                 </div>
                 {% endfor %}
             </div>
             <div class="mx-auto">
                 {% if pro.paginator.num_pages > 1 %}
                  <hr>
                 <div class="text-center">
                     {% for j in pro.paginator.page_range %}
                         <a href="?page={{j}}" class="btn btn-light btn-sm {% if pro.number == j %} active {% endif %}">{{j}}</a>
                     {% endfor %}
                 </div>
                 {% endif %}
             </div>
             <br>
         </div>
{% endblock %}

templates/footer.html
<div class="footer navbar-fixed-bottom myfooter">
    <p class="text-center">@copy; ecommerce pvt ltd.All rights Reserved</p>
</div>

templates/header.html
{% load static %}
<header>
    <center>
        <a href="{% url 'ecommerceapp:allproducts' %}"> <img src="{% static 'images/logo.png' %}"  alt="logimage" style="width:100px"></a>
    </center>
</header>

templates/nav.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <a class="nav-link" href="/">Home</a>
        </li>
        <li class="nav-item dropdown {% if 'ecommerceapp' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Shop
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'ecommerceapp:allproducts' %}">All Products</a></li>
              {% for j in links %}
            <li><a class="dropdown-item" href="{{j.get_url}}">{{j.name}}</a></li>
               {% endfor %}
          </ul>
        </li>
        {% if item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link " href="{% url 'cartapp:cart_detail' %}"><i class="fa-solid fa-cart-shopping"></i>({{item_count}})</a>
        </li>
        {% endif %}
      </ul>
      <form class="d-flex" action="{% url 'searchapp:search' %}" method="get">
      {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><i class="fa-solid fa-magnifying-glass"></i>Search</button>
      </form>
    </div>
  </div>
</nav>

templates/product_detail.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

{{pro1.description|truncatewords:155}}

{% endblock %}

{% block title %}
   {% if c_page %}
         {{pro1.name }}
   {% endif %}
{% endblock %}

{% block content %}
<div class="row myproduct-class">
    <div class="mx-auto">
        <p> <a href="{% url 'ecommerceapp:allproducts' %}">Home</a> | <a href="{{pro1.c_page.get_url}}">{{pro1.c_page}}</a> | {{pro1.name}} </p>
    </div>
</div>
<div class="container">
   <br>
   <div class="row">
      <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
          <div style="min-width:18rem">
             <img src="{{pro1.image.url}}" alt="{{pro1.name}}" style="width:200px">
          </div>
      </div>

<div class="col-12 col-sm-12 col-md-12 col-lg-6">

    <div>
        <h1 class="myproduct-title">{{pro1.name}}</h1>
        <p>${{pro1.price}}</p>
        <p class="mytitle">Product Description</p>
        <p class="text-justify myproduct-text">{{pro1.description}}</p>
        {% if pro1.stock <= 0 %}
        <p class="text-justify myproduct-text">!!Out Of Stock!!</p>
        {% else %}
        <a class="btn btn-secondary" href="{% url 'cartapp:add_cart' pro1.id %}">Add To Cart</a>
        {% endif %}
    </div>
</div>
</div>
    </div>
{% endblock %}

templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    we have variety of products
{% endblock %}
{% block title %}
Search
{% endblock %}
{% block content %}
<div>
    <p class="text-center mysearch">you have searched for:<b>"{{query}}"</b></p>
</div>
<div class="container">
             <div class="row mx-auto">
                 {% for i in pro.object_list %}
                 <div class="my-bottom-margin col-9 col-sm-12 col-md-4  xol-lg-4">
                     <div class="card text-center" style="min-width:18rem">
                     <a href="{{i.get_url}}"><img class="card-img myimage" src="{{i.image.url}}"  alt="{{i.name}}"></a>
                     <div class="card-body">
                         <h4>{{i.name}}</h4>
                         <p>${{i.price}}</p>
                     </div>
                     </div>
                 </div>
                 {% empty %}
                 <div class="row mx-auto">
                     <p class="text-center mysearch">0 results found</p>
                 </div>
                 {% endfor %}
             </div>
</div>

{% endblock %}